logging:
  level:
    ru.sadovskie.leo.app.joposcragent.jobpostingscrud: INFO

management:
  endpoint:
    enabled-by-default: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: job-postings-crud
  datasource:
    url: jdbc:postgresql://localhost:5432/joposcragent
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: job-postings-crud
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    enabled: true
    job-posting-create-consumer-group: job-postings-crud-job-posting-create

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    ru.sadovskie.leo.app.joposcragent.jobpostingscrud: DEBUG

server:
  port: 8089

---
spring:
  config:
    activate:
      on-profile: protozoa

server:
  port: 8089